//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CatalogId { get; set; }
        public string Picture { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> ProductSold { get; set; }
        public string ProductSale { get; set; }
        public Nullable<double> PriceOld { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
